// lib/giadungSeed.js
// Danh sách sản phẩm "Gia dụng + Thực phẩm chức năng" được tự động điền từ
// file Google Sheet "BẢNG GIÁ GỒM CÂN" (sheet "GIA DỤNG, THỰC PHẨM CHỨC NĂNG")
// do chủ shop cung cấp. Dùng làm dữ liệu khởi tạo (seed) một lần khi tab này
// còn trống — sau khi người dùng tự thêm/sửa/xoá sản phẩm, danh sách thật sẽ
// được lưu và seed này không còn tác dụng nữa.
export const SEED_GIADUNG = [
  {
    id: "g01",
    name: "Viên uống bổ sung Magie Health+ (60 viên nén, dùng 30 ngày)",
    link: "",
    jpy: "",
    vnd: "Theo giá sẵn",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Hàng bán sẵn, xem giá sẵn hiện có.",
  },
  {
    id: "g02",
    name: "Lọ chống mọt gạo",
    link: "https://www.amazon.co.jp/dp/B002ROPIFE/?th=1",
    jpy: "",
    vnd: "150k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "cQA nhập về bán sẵn rồi nên lưu đơn thì lưu sẵn siêu thị nhé, giá 150k.\nBài đăng: https://www.facebook.com/reel/1891080824897410",
  },
  {
    id: "g03",
    name: "Giá phơi bát đĩa gấp gọn Pearl Metal HB-6355 Kitchen Mate",
    link: "https://www.amazon.co.jp/dp/B09TSDXK4T",
    jpy: "885y",
    vnd: "390k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/1HURtWU6Gu/",
  },
  {
    id: "g04",
    name: "Lọ xay muối tiêu Asvel",
    link: "https://www.amazon.co.jp/dp/B003NUSDDK/",
    jpy: "825y",
    vnd: "260k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://web.facebook.com/share/r/1H9zamHFJQ/",
  },
  {
    id: "g05",
    name: "Chảo gang TETSUNAGI (vuông & tròn, nhiều kích thước)",
    link: "https://www.amazon.co.jp/dp/B0H2TYLN7J?th=1",
    jpy: "",
    vnd: "Không tính giá gồm cân, báo giá +KG bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Nhận order cả loại vuông và tròn với nhiều kích thước.\nBài đăng: https://web.facebook.com/share/p/1BRvBA7jd8/",
  },
  {
    id: "g06",
    name: "Bình đựng đá Atlas AWJB-A3900",
    link: "https://www.amazon.co.jp/dp/B0G293Z4Q3?th=1",
    jpy: "",
    vnd: "Không tính giá gồm cân, báo giá +KG bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Nhận order cả loại 2.3l và 3.9l với 2 màu khác nhau.\nBài đăng: https://web.facebook.com/share/p/1Bc8gSS2Jw/",
  },
  {
    id: "g07",
    name: "Máy hút bụi cầm tay mini Svoko",
    link: "https://www.amazon.co.jp/dp/B0DC6FB2C5?th=1",
    jpy: "2999y",
    vnd: "795k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/r/18nNpNhxrn/",
  },
  {
    id: "g08",
    name: "Quạt tuần hoàn Amazon",
    link: "https://www.amazon.co.jp/dp/B0C9ZT34H3",
    jpy: "6482y",
    vnd: "1790k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/1HGT3AmUmF/",
  },
  {
    id: "g09",
    name: "Vòi sen Refa",
    link: "https://www.amazon.co.jp/dp/B0G23VZNCX",
    jpy: "Màu trắng + màu bạc giá 35.000y, các màu còn lại giá 38.000y",
    vnd: "Màu trắng và bạc 6990k, còn lại 7590k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/r/1BYc7FbQVG/",
  },
  {
    id: "g10",
    name: "Cây lau nhà tắm LEC S-824 Gekochi-kun",
    link: "https://www.amazon.co.jp/-/en/dp/B01KUSQ50A?th=1",
    jpy: "",
    vnd: "Có loại cán ngắn và cán dài, có cả lựa chọn set 2 cái, mỗi loại 1 giá — không tính giá gồm cân, báo +KG như bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/1DTgVg7qUw/",
  },
  {
    id: "g11",
    name: "Nồi chiên điện Zojirushi",
    link: "https://www.amazon.co.jp/-/en/dp/B001RO4H7U",
    jpy: "",
    vnd: "Không tính giá gồm cân, báo giá +KG bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/18spDPwuBL/",
  },
  {
    id: "g12",
    name: "Máy sấy Komidy",
    link: "https://www.amazon.co.jp/Komidy/dp/B0GXFM564B?th=1",
    jpy: "",
    vnd: "Không tính giá gồm cân, báo giá +KG bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g13",
    name: "Khăn tắm sợi gai",
    link: "https://www.amazon.co.jp/dp/B003PBTWE6?th=1",
    jpy: "746y/cái",
    vnd: "190k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/reel/1008345242170469",
  },
  {
    id: "g14",
    name: "Máy làm đá bào",
    link: "https://www.amazon.co.jp/-/en/dp/B0BV1YRN8Y?th=1",
    jpy: "Loại màu be chạy bằng điện, loại màu xanh mint chạy bằng pin",
    vnd: "Tự tính giá trên web cộng cân nặng sản phẩm 1.2kg",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g15",
    name: "Lược gội đầu Mapepe",
    link: "https://www.amazon.co.jp/dp/B001H9NQ1I/?th=1",
    jpy: "638y",
    vnd: "250k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/r/1RMm7PN6XQ/",
  },
  {
    id: "g16",
    name: "Bộ dao kéo T-Fal tráng Titanium K13403",
    link: "https://www.amazon.co.jp/dp/B0GWKWBG16/?th=1",
    jpy: "4805y cả bộ 4 món",
    vnd: "980k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Có lựa chọn lẻ dao hoặc lẻ kéo.\nBài đăng: https://www.facebook.com/share/p/18mjP9oeJk/",
  },
  {
    id: "g17",
    name: "Bàn chải điện Baometi (kèm 8 đầu bàn chải thay thế)",
    link: "https://www.amazon.co.jp/dp/B0GX1K9T3N/?th=1",
    jpy: "Nhận gom 2 màu onyx và vanilla, giá 2980y và 2979y",
    vnd: "695k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/14q3idnkGHy/",
  },
  {
    id: "g18",
    name: "Bình nước Asvel 2L",
    link: "https://www.amazon.co.jp/-/en/dp/B0CZSPP7R3?th=1",
    jpy: "1192y/bình, 2384y/set 2 bình",
    vnd: "425k/bình, set 2 bình 795k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/1BQWb5Aqqh/",
  },
  {
    id: "g19",
    name: "Nồi chiên không dầu Wallfire",
    link: "https://www.amazon.co.jp/dp/B092ZS3LLB/",
    jpy: "",
    vnd: "Không tính giá gồm cân, báo giá +KG bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/173RhG7EWS/",
  },
  {
    id: "g20",
    name: "Hạt Chia",
    link: "",
    jpy: "",
    vnd: "Khách hỏi thì báo giá 350k/túi 300g",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Hàng có sẵn.\nBài đăng: https://www.facebook.com/share/r/1cvbdkRqy8/",
  },
  {
    id: "g21",
    name: "Sạc dự phòng 50.000mAh",
    link: "https://www.amazon.co.jp/dp/B0GSZ3D29K?th=1",
    jpy: "2849y",
    vnd: "690k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/1BUfSChD1o/",
  },
  {
    id: "g22",
    name: "Bình trà lõi lọc Asvel",
    link: "https://www.amazon.co.jp/dp/B085TTNXLD/?th=1",
    jpy: "999y",
    vnd: "290k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g23",
    name: "Máy xay cà phê điện BESROY",
    link: "https://www.amazon.co.jp/dp/B0B6RCRH22/?th=1",
    jpy: "2980y",
    vnd: "690k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/19DyxiuFA9/",
  },
  {
    id: "g24",
    name: "Set gội xả Bioliss",
    link: "https://item.rakuten.co.jp/rakuten24/4971710642414/",
    jpy: "1090y",
    vnd: "440k/cặp gội xả",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Màu vàng cho đầu nhiều dầu, màu cam cho tóc khô xơ hoặc dùng nhiều hóa chất.\nLink thay thế (Amazon): https://www.amazon.co.jp/dp/B0GTSSWWJD/\nBài đăng: https://www.facebook.com/share/p/18Nt22R6it/",
  },
  {
    id: "g25",
    name: "Tinh dầu thơm phòng cắm que Sawaday",
    link: "https://www.amazon.co.jp/dp/B0BYRRVN55/",
    jpy: "Màu vàng và xanh 496y, màu đen 1848y",
    vnd: "Màu vàng và màu xanh 190k, màu đen 220k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Màu vàng: https://www.amazon.co.jp/dp/B0BYRRVN55/\nMàu xanh: https://www.amazon.co.jp/dp/B0DGKPX854/\nMàu đen: https://www.amazon.co.jp/dp/B017I9P4I8/",
  },
  {
    id: "g26",
    name: "Chảo siêu nhẹ KAI",
    link: "https://www.amazon.co.jp/-/dp/B002GGRDSI/",
    jpy: "",
    vnd: "Dựa theo cân nặng sản phẩm từng size để tự tính giá gồm cân, tính chênh thêm khoảng 2 lạng so với cân nặng sản phẩm ghi trên web",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Chọn phân loại Frying Pan Induction Compatible, mỗi size 1 giá — chú ý hỏi khách chọn size nào thì báo giá size đó.\nBài đăng: https://www.facebook.com/share/p/1cMsa79JaK/",
  },
  {
    id: "g27",
    name: "Máy sấy chăn ga gối đệm chống mạt bụi Sintu",
    link: "https://www.amazon.co.jp/dp/B0GF86JSRR/",
    jpy: "5776y",
    vnd: "1395k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g28",
    name: "Máy xay Panasonic",
    link: "https://www.amazon.co.jp/dp/B09W5FZ8W3?th=1",
    jpy: "Chỉ nhận phân loại Entry: 8003y",
    vnd: "1890k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/r/18pW8PXJ7u/",
  },
  {
    id: "g29",
    name: "Nạo rau củ đa năng Shimomura Kihan 4 in 1",
    link: "https://www.amazon.co.jp/dp/B0793NSD3M?th=1",
    jpy: "1041y",
    vnd: "360k/1 set",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Màu trắng.",
  },
  {
    id: "g30",
    name: "Xịt tẩy nhà bếp KAO",
    link: "",
    jpy: "",
    vnd: "240k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Tẩy bình giữ nhiệt, thớt,... Có sẵn siêu thị. C QA đăng trên tiktok của c QA.",
  },
  {
    id: "g31",
    name: "Táo đỏ",
    link: "https://www.amazon.co.jp/gp/aw/d/B0CZTFZHHK/?th=1",
    jpy: "1480y",
    vnd: "350k/1 gói 268g",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g32",
    name: "Kỷ tử",
    link: "https://www.amazon.co.jp/dp/B0D1RDRGNR/?th=1",
    jpy: "",
    vnd: "Gói 168g: sale còn 980y thì tính 290k gồm cân, không sale mà 1180y thì tính 335k gồm cân. Gói 328g: sale còn 1750y thì tính 480k gồm cân, không sale mà 1980y...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Link gói 328g: https://www.amazon.co.jp/dp/B0D1RH31WP/?th=1",
  },
  {
    id: "g33",
    name: "Bột protein 1kg",
    link: "https://www.amazon.co.jp/dp/B01FRPR17W?th=1",
    jpy: "4360y",
    vnd: "1050k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g34",
    name: "Bột yến mạch OatMeal 1kg",
    link: "https://www.amazon.co.jp/dp/B0B46BHLY2/?th=1",
    jpy: "955y",
    vnd: "390k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g35",
    name: "7 loại hạt mix 350g",
    link: "https://www.amazon.co.jp/dp/B07XLX7LXJ/?th=1",
    jpy: "1000y",
    vnd: "330k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g36",
    name: "Các loại hạt nấu cùng cơm",
    link: "https://item.rakuten.co.jp/buono-buono/10007800-2pc/",
    jpy: "1000y",
    vnd: "250k/1 gói 400gr, 450k/2 gói tổng 800gr",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Link trên là gói 2 túi tổng 800g. Link gói lẻ 400g thì phải hỏi lại đã.",
  },
  {
    id: "g37",
    name: "Thớt kháng khuẩn",
    link: "",
    jpy: "1280y",
    vnd: "450k (áp dụng cho giá yên 1280y)",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Hiện đã có sẵn siêu thị. Hàng siêu thị hết thì hỏi xem có về nữa không, chỉ khi nào không về thêm hàng siêu thị nữa thì mới nhận order theo giá trên.",
  },
  {
    id: "g38",
    name: "Dao liền khối KAI",
    link: "https://www.amazon.co.jp/dp/B06Y2WQMNG?th=1",
    jpy: "",
    vnd: "Nhiều mức giá — 610k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\nChủ yếu nhận dòng phân loại Chef Knife (là dòng cắt thái đa năng)\n- Size 18cm 2736y -> 610k gồm cân\n- Size 21cm 3109y -> 695k gồm cân\n- Size 24cm 3945y -> 870k gồm cân\n\n\nCác phân loại dòng khác ngoài phân loại Chef Knife thì tính bình thường",
  },
  {
    id: "g39",
    name: "bàn ủi hơi nc không dây Toshiba",
    link: "https://www.amazon.co.jp/dp/B07HMM95HZ/?th=1",
    jpy: "",
    vnd: "tính bth, không có giá gồm cân",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g40",
    name: "Thớt rã đông Atomico",
    link: "https://www.amazon.co.jp/dp/B0DB1PKJVY/?th=1",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "Nhiều mức giá — 250k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\nsize S: 250k\nsize M: 350k\n\nGiá Yên chi tiết:\nsize S: 936y\nsize M: 1264y",
  },
  {
    id: "g41",
    name: "Chảo sắt TAKUMI JAPAN",
    link: "https://www.amazon.co.jp/dp/B01MG9GVDG/?th=1",
    jpy: "gom size 15x19cm: 2736y",
    vnd: "size 15x19cm giá 695k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g42",
    name: "Nước hoa Maiko Dream Cologne hương mộc hương",
    link: "https://www.amazon.co.jp/dp/B0761NMQS1",
    jpy: "1340y",
    vnd: "320k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g43",
    name: "Xịt họng keo ong Propolis Ginger",
    link: "https://www.amazon.co.jp/dp/B0B5B7WD73/",
    jpy: "2200",
    vnd: "460k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g44",
    name: "Set chậu rổ của KAI (Chú ý note đúng link)",
    link: "https://www.amazon.co.jp/dp/B0FGCF6JMF/?th=1",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "Nhiều mức giá — 1190k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Set 6 món(3 chậu+3 rổ): https://www.amazon.co.jp/dp/B0FGCF6JMF/?th=1\n\nSet 3 chậu: https://www.amazon.co.jp/dp/B0B4ND6NVY/?th=1\n\nSet 3 rổ: https://www.amazon.co.jp/dp/B0B4NCW4JJ/?th=1\n\nGiá gồm cân chi tiết:\nSet 6 món 1190k\nSet 3 chậu 690k\nSet 3 rổ 690k\n\nGiá Yên chi tiết:\nset 6 món 3980y\nset 3 chậu 2200y\nset 3 rổ 2200y",
  },
  {
    id: "g45",
    name: "Vòi sen RUNCTY",
    link: "https://www.amazon.co.jp/dp/B0D3Q2RTN9?th=1",
    jpy: "2919y",
    vnd: "890k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g46",
    name: "Ghế công thái học Foxkoo",
    link: "https://www.amazon.co.jp/dp/B0GXB3KK1Z/?th=1",
    jpy: "",
    vnd: "Xem ghi chú giá",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\nkhông báo giá gồm cân mà tính giá +Kg như bình thường nhé",
  },
  {
    id: "g47",
    name: "nạo rau 2 lưỡi Noji",
    link: "https://www.amazon.co.jp/dp/B08MDYDCZC/?th=1",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "Nhiều mức giá — 280k...",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "màu xanh: https://www.amazon.co.jp/dp/B08MDYDCZC/?th=1\n\nmàu trắng: https://www.amazon.co.jp/dp/B0D974X5VG/?th=1\n\nGiá gồm cân chi tiết:\nmàu xanh 280k (đã có sẵn, lưu đơn siêu thị nhé)\n\nmàu trắng 395k\n\nGiá Yên chi tiết:\nmàu xanh 927y\n\nmàu trắng 1540y",
  },
  {
    id: "g48",
    name: "hộp hấp thức ăn 2 tầng Astro",
    link: "https://www.amazon.co.jp/dp/B0DX6VY8B4/?th=1",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "490k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá Yên chi tiết:\nphân loại  Steamer, 2 Tier nhé: \n2000y",
  },
  {
    id: "g49",
    name: "máy xay tay Toffy",
    link: "https://www.amazon.co.jp/dp/B08HYYTW5M/?th=1",
    jpy: "1320y",
    vnd: "350k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g50",
    name: "Quánh Yoshikawa 18cm",
    link: "https://item.rakuten.co.jp/premoa/4979487767521/?s-id=ph_pc_itemimage",
    jpy: "3127y",
    vnd: "Nhiều mức giá — 750k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Link rakuten: \nhttps://item.rakuten.co.jp/premoa/4979487767521/?s-id=ph_pc_itemimage \nLink amazon: https://www.amazon.co.jp/dp/B001BASSR0/?th=1\n\nGiá gồm cân chi tiết:\nCứ dưới 3127y thì đều tính 750k gồm cân, lúc lưu đơn chọn xem link rakuten với amazon link nào r9i hçn thì lưu link đó",
  },
  {
    id: "g51",
    name: "Hộp chia nhỏ thực phẩm Pearl Metal",
    link: "https://www.amazon.co.jp/dp/B0CM667QP8/?th=1",
    jpy: "750y",
    vnd: "250k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g52",
    name: "máy xay tiếu tự động Russell Hobbs",
    link: "https://www.amazon.co.jp/dp/B0CY4TMTST?th=1",
    jpy: "3800y",
    vnd: "790k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g53",
    name: "Khăn lau bếp và kính đa năng Marna",
    link: "https://www.amazon.co.jp/dp/B08VN75Z73/?th=1",
    jpy: "586y đổ xuống",
    vnd: "130k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g54",
    name: "Xịt xà phòng tự động",
    link: "https://www.amazon.co.jp/dp/B0FK1XQSK8/?th=1",
    jpy: "1978y",
    vnd: "Nhiều mức giá — 490k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\n1978y thì giá gồm cân 490k\n2180y thì giá gồm cân 520k",
  },
  {
    id: "g55",
    name: "Chõ hấp thức ăn bằng thép",
    link: "https://www.amazon.co.jp/dp/B003OBWBIQ/?th=1",
    jpy: "1230y trở xuống đều được",
    vnd: "330k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "size 14-24cm: https://www.amazon.co.jp/dp/B003OBWBIQ/?th=1\n\nsize 17.5-27cm: https://www.amazon.co.jp/dp/B003OBQKAQ/?th=1",
  },
  {
    id: "g56",
    name: "Miếng lót bếp từ",
    link: "https://www.amazon.co.jp/dp/B07BBXDXMV?th=1",
    jpy: "427y/1 miếng",
    vnd: "125k/1 miếng",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Chú ý đây là link 1 miếng, thường khách sẽ mua theo cặp cho 2 bên bếp thì lúc lưu đơn phải lưu số lượng 2: https://www.amazon.co.jp/dp/B07BBXDXMV?th=1",
  },
  {
    id: "g57",
    name: "Gối công thái học",
    link: "https://www.amazon.co.jp/dp/B0H4JNG39Y/",
    jpy: "",
    vnd: "Nhiều mức giá — 490k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\n1980y tính 490k\n2180y tính 530k",
  },
  {
    id: "g58",
    name: "Xịt tẩy rửa dầu mỡ Gekiochi-kun Sesquicarbonate Spray 400ml không màu không mùi",
    link: "",
    jpy: "",
    vnd: "230k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "sẵn siêu thị",
  },
  {
    id: "g59",
    name: "Dập tỏi KAI",
    link: "https://www.amazon.co.jp/dp/B0009WCIHM/?th=1",
    jpy: "1418y",
    vnd: "370k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g60",
    name: "Bình trà Hario có lưới lọc 700ml",
    link: "https://www.amazon.co.jp/dp/B002GYVDKO/?th=1",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g61",
    name: "Cốc thermos nắp trượt 500ml",
    link: "https://www.amazon.co.jp/dp/B0CCRKTDZ8/?th=1",
    jpy: "2209y",
    vnd: "480k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g62",
    name: "Đai lưng chỉnh tư thế DEZIYUA",
    link: "https://www.amazon.co.jp/dp/B0CXQB1FTR/",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá Yên chi tiết:\nChú ý khi tư vấn cho khách sẽ có bảng size phần thông tin sản phẩm trong link amazon, mỗi size có 1 mã asin và có giá riêng",
  },
  {
    id: "g63",
    name: "Kem tẩy mảng bám trên bếp từ",
    link: "https://www.amazon.co.jp/dp/B0196076X8/",
    jpy: "",
    vnd: "160k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g64",
    name: "Bình giữ nhiệt thermos 1.2l",
    link: "https://www.amazon.co.jp/dp/B07NGLSQ62?th=1",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g65",
    name: "Viên làm sạch đường ống Kobayashi",
    link: "https://www.amazon.co.jp/dp/B0012PB0SS?th=1",
    jpy: "",
    vnd: "120k vỉ 12 viên",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g66",
    name: "Nồi nấu bằng lò vi sóng",
    link: "https://www.amazon.co.jp/dp/B07SPRGHMC?th=1",
    jpy: "524y",
    vnd: "190k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g67",
    name: "Máy ép chậm HUrom",
    link: "https://www.amazon.co.jp/dp/B0G6JB741M/?th=1",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Clip review đồ gia dụng của c QA\n\nDạ mẫu máy ép chậm Hurom H26 trong video mua từ 6 năm trước, hiện ź Nhật đã ngẻng bán mất r ạ, a/c tham khảo giúp em sang 2 mẫu mới nhất này nha:\n- Hurom H310A bản size mini, thiết kế gọn nhẹ, dễ vệ sinh: https://www.amazon.co.jp/dp/B0G6JB741M/?th=1\n\n- Hurom H400, bản xịn sò và cải tiến hơn so với bản H26 cũ rét nhiều: Có thể cho nguyên quả (như táo, cà chua) hoặc một lượng lớn rau củ mà không cần cắt thái nhỏ. Sử dụng bộ lọc kép dạng rãnh All-in-One (tất cả trong một) và dùng chung một bộ lọc này để ép nước, làm sinh tố hoặc làm kem từ trái cây đông lạnh mà không cần tháo đổi phụ kiện. Cấu trúc bộ lọc ít chi tiết rườm rà, không có các lỗ ti vi nhỏ dể bám cặn, việc xả nước và cọ rỪa diễn ra rát nhanh chóng: https://www.amazon.co.jp/dp/B0CD9NLCGK/?th=1",
  },
  {
    id: "g68",
    name: "Nồi cơm điện Zojirushi",
    link: "https://www.amazon.co.jp/dp/B088FZXZHY",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Clip review đồ gia dụng của c QA",
  },
  {
    id: "g69",
    name: "Bình đun nước Zojirushi",
    link: "https://www.amazon.co.jp/dp/B074FWJPCY?th=1",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Clip review đồ gia dụng của c QA",
  },
  {
    id: "g70",
    name: "Bộ nồi chảo Iris Ohyama Ceramic",
    link: "https://www.amazon.co.jp/dp/B0C1JX1PWH/?th=1",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Clip review đồ gia dụng của c QA\n\nSet nồi chảo Iris Ohyama màu vàng trong clip e đăng hiện k còn hàng, c tham khảo sang các màu trong link này cũng xinh k kém đâu ạ: https://www.amazon.co.jp/dp/B0C1JX1PWH/?th=1\nHiện có các set 6 món, 9 món, 12 món, 13 món hoặc 14 món. C chọn màu và set mấy món thì báo em để em check giá cho c nha\n\nGiá Yên chi tiết:\nChú ý có phân loại set 6 món, 8 món, 9 món, 12 món , 13 món, 14 món và có 2 màu hồng với be. Mỗi phân loại và màu có giá khác nhau, phải hỏi khách xem khách chọn gì trước mới báo giá",
  },
  {
    id: "g71",
    name: "Lò vi sóng Sharp",
    link: "https://www.amazon.co.jp/dp/B07M8VBL6C/?th=1",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Clip review đồ gia dụng của c QA",
  },
  {
    id: "g72",
    name: "Đá tẩy lông",
    link: "https://www.amazon.co.jp/dp/B0F9KQVTQQ/?th=1",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "360k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá Yên chi tiết:\nNhận order màu xanh dương, đen và xanh lá cây, giá từ 1527y đổ xuống",
  },
  {
    id: "g73",
    name: "Xịt vệ sinh gia dụng Kao Easy My Pet Handy Spray 400ml khử trùng diệt vi khuẩn",
    link: "",
    jpy: "",
    vnd: "220k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Clip review phòng khách\n\nsẵn siêu thị",
  },
  {
    id: "g74",
    name: "Tấm nhựa PVC trải bàn",
    link: "https://item.rakuten.co.jp/moresmileshop/ph-17000p400/",
    jpy: "",
    vnd: "Nhiều mức giá — 190k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Clip review phòng khách\n\nGiá gồm cân chi tiết:\nGiá web * 220 + cân nặng cho từng kích thước ước tính như dưới đây, tự nhân 190k để báo khách:\n(CHÚ Ý CÂN NẶNG CHỈ ƯỚC TÍNH CHƯA CHÍNH XÁC -> BÁO KHÁCH ĐÂY CHỈ LÀ PHÍ VC ƯỚC TÍNH THÔI NHÉ!)\n40 × 60 cm          ~1,5 kg\n60 × 120 cm        ~2,5 kg\n60 × 140 cm        ~3 kg\n70 × 120 cm        ~3 kg\n70 × 140 cm        ~3,5 kg\n80 × 80 cm          ~2,5 kg\n80 × 120 cm        ~3,5 kg\n80 × 135 cm        ~4 kg\n80 × 140 cm         ~4 kg\n80 × 150 cm         ~4,5 kg\n90 × 150 cm        ~4,5 kg\n90 × 160 cm        ~5 kg",
  },
  {
    id: "g75",
    name: "Máy giặt thảm Uwant",
    link: "https://www.amazon.co.jp/dp/B0H3ZP747G/?th=1",
    jpy: "chỉ gom màu cappuccino 8980y",
    vnd: "Nhiều mức giá — 2980k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\n890Y thì giá gồm cân là 2980k\nBáo giá cho khách bằng câu này:\n\nDạ c ui, máy giặt vệ sinh thảm đệm sofa chính hãng Uwant Y100JP giá order 2980k c nha, giá này e đang gom là giá tốt nhất thị trường.\n\nTại VN hiện hầu như chỉ bán dòng B100 với mức giá thấp nhất cũng từ 4tr trở lên ý. So với B100 thì dòng Y100 em gom có cải tiến công nghệ hơn, lực hút mạnh hơn, đẹp và gọn nhẹ hơn. e gom từ nội địa Nhật đang sale mới có giá này đó ạ.",
  },
  {
    id: "g76",
    name: "Set 9 món Carote",
    link: "https://www.amazon.co.jp/dp/B0CC9B349C?th=1",
    jpy: "1852y",
    vnd: "595k cả bộ",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g77",
    name: "Bình đựng dầu CB JAPAN",
    link: "https://www.amazon.co.jp/dp/B0DBYKKC51?th=1",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "Nhiều mức giá — 350k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\nchai nhỏ 350k, chai to 360k. Hướng khách mua chai to nhé\n\nGiá Yên chi tiết:\n- chai nhỏ dung tích lên tới 300ml giá 1442y\n- chai to dung tích lên tới 500ml giá 1476y",
  },
  {
    id: "g78",
    name: "Bình xịt dầu CAINZ 170ml",
    link: "https://www.amazon.co.jp/dp/B0FN2ZRHDR",
    jpy: "498y",
    vnd: "200k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g79",
    name: "Máy xay cầm tay Ninja",
    link: "https://www.amazon.co.jp/dp/B0D1TLJNDQ/?th=1",
    jpy: "7700y",
    vnd: "Xem ghi chú giá",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\n1tr5 (nhiều màu nhưng giá các màu đều bằng nhau),  nhớ hỏi xem khách lấy màu nào nhé)",
  },
  {
    id: "g80",
    name: "Bộ khoan vít không dây Pycuse",
    link: "https://www.amazon.co.jp/dp/B0H5HC596P/?th=1",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g81",
    name: "Set 2 muôi inox IMEEA",
    link: "https://www.amazon.co.jp/dp/B0823J67MB/",
    jpy: "1999y",
    vnd: "490k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g82",
    name: "Set bút bi Zebra",
    link: "https://www.amazon.co.jp/dp/B00APA1F3G/?th=1",
    jpy: "tầm 700y đổ xvống",
    vnd: "220k/set",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "màu xanh: https://www.amazon.co.jp/dp/B00APA1F3G/?th=1\n \nmàu đen: https://www.amazon.co.jp/dp/B00P0PT7BS/",
  },
  {
    id: "g83",
    name: "Bộ nồi chiên rán kèm khay Pearl Metal",
    link: "https://item.rakuten.co.jp/rakuten24/4549308713299/",
    jpy: "2734y",
    vnd: "790k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g84",
    name: "Khay inox vuông kèm vỉ lưới đa năng",
    link: "https://www.amazon.co.jp/dp/B088ZDVZJV/?th=1",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "Nhiều mức giá — 390k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Chỉ nhận loại Stand Set, vỉ lưới đi kèm có thể dựng lên được\nSize S: https://www.amazon.co.jp/dp/B088ZDVZJV/?th=1 \nSize M: https://www.amazon.co.jp/dp/B088ZDVZJV/?th=1\n\nGiá gồm cân chi tiết:\nSize S giá về tay 390k\nSize M giá về tay 590k\n\nGiá Yên chi tiết:\nSize S 1364y\nSize M 1958y",
  },
  {
    id: "g85",
    name: "Chai đựng mắm iwaki 250ml",
    link: "https://www.amazon.co.jp/dp/B003S9WINC/?th=1",
    jpy: "1582y",
    vnd: "390k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g86",
    name: "Khay treo bàn chải Yamazaki",
    link: "https://www.amazon.co.jp/dp/B0CC8LT6RJ?th=1",
    jpy: "chỉ nhận màu trắng: 2322y",
    vnd: "590k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g87",
    name: "Muôi múc canh KAI",
    link: "https://www.amazon.co.jp/dp/B09RQMKCYB/",
    jpy: "1073y",
    vnd: "290k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g88",
    name: "Muôi lỗ Nonoji",
    link: "https://www.amazon.co.jp/dp/B081DZLP15/?th=1",
    jpy: "1438y",
    vnd: "370k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g89",
    name: "Nạo rau củ inox KAI",
    link: "https://www.amazon.co.jp/dp/B0009WCIDQ?th=1",
    jpy: "936y",
    vnd: "250k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g90",
    name: "Kem đánh răng ora",
    link: "",
    jpy: "",
    vnd: "150k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Có sẵn siêu thị",
  },
  {
    id: "g91",
    name: "Quạt đối lưu tuần hoàn Iris Ohyama PCF-MKM15EC-W",
    link: "https://www.amazon.co.jp/dp/B0G6KCNKVH/?th=1",
    jpy: "2600y",
    vnd: "950k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Chỉ nhận order phân loại màu white- Left and right oscillating (fully disassembled) đúng theo link này:  https://www.amazon.co.jp/dp/B0G6KCNKVH/?th=1",
  },
  {
    id: "g92",
    name: "Hộp đựng gia vị marna",
    link: "https://biccamera.rakuten.co.jp/item/4976404273615/?variantId=4976404273615",
    jpy: "1078y",
    vnd: "290k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g93",
    name: "Khay lọc rác bồn rửa bát",
    link: "https://item.rakuten.co.jp/lamd/10058176/",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "Nhiều mức giá — 300k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Có nắp: https://item.rakuten.co.jp/lamd/10058176/\nKhông nắp: https://www.amazon.co.jp/dp/B06XWPXFXG/?th=1\n\nGiá Yên chi tiết:\nCó nắp 1054y\nKhông nắp 1073y\n\nGiá gồm cân chi tiết:\nKhông nắp 300k\nCó nắp 390k",
  },
  {
    id: "g110",
    name: "hộp trữ cơm nguội",
    link: "https://www.amazon.co.jp/dp/B0F9D8LWVQ/?th=1",
    jpy: "1680y set 4 hộp",
    vnd: "470k set 4 hộp",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g111",
    name: "mài dao KAI",
    link: "https://www.amazon.co.jp/dp/B0061WZ7A4/?th=1",
    jpy: "1364y",
    vnd: "360k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Chỉ nhận Phân loại For double-edged knives | Seki Magoroku: https://www.amazon.co.jp/dp/B0061WZ7A4/?th=1",
  },
  {
    id: "g112",
    name: "Cọ bồn cầu Marna",
    link: "https://www.amazon.co.jp/dp/B000L1YK22?th=1",
    jpy: "1773y",
    vnd: "460k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g113",
    name: "Iris Ohyama LDL-QLDL-W-màu trắng",
    link: "https://www.amazon.co.jp/dp/B08LG1JS2M/r?th=1",
    jpy: "5520y",
    vnd: "1390k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "chỉ nhận phân loại màu trắng-Smartphone stand model theo link:\nhttps://www.amazon.co.jp/dp/B08LG1JS2M/r?th=1",
  },
  {
    id: "g114",
    name: "rổ quay rau Yamaken",
    link: "https://www.amazon.co.jp/dp/B0DZFTK6RD/?th=1",
    jpy: "1080y",
    vnd: "330k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "chỉ nhận phân loại 02:Standard theo link: \nhttps://www.amazon.co.jp/dp/B0DZFTK6RD/?th=1",
  },
  {
    id: "g115",
    name: "rây lọc nấu ăn",
    link: "https://www.amazon.co.jp/dp/B096VQ7V2N/?th=1",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "Nhiều mức giá — 390k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá Yên chi tiết:\nsize 18cm: 1267y\nSize 21cm: 1487y\n\nGiá gồm cân chi tiết:\nSize 18: 390k\nSize 21: 435k\n(Chủ yếu nhận đơn size 18cm, nhưng khách hỏi có size to hơn không thì vẫn nhận thêm cả size 21cm nhé)",
  },
  {
    id: "g116",
    name: "máy cạo râu Philips",
    link: "https://www.amazon.co.jp/dp/B09TPSTJLV?th=1",
    jpy: "7920y",
    vnd: "1690k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Chỉ nhận phân loại S5000 / SINGLE:\nhttps://www.amazon.co.jp/dp/B09TPSTJLV?th=1",
  },
  {
    id: "g117",
    name: "Hút bụi dyson Digital Slim Origin (SV18 FF OR2 AM)",
    link: "https://www.amazon.co.jp/dp/B0DZ2PC71L?th=1",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g118",
    name: "Cân omron",
    link: "https://www.amazon.co.jp/dp/B0DF78D991?th=1",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g119",
    name: "set 3 khăn tắm Kenkyujo",
    link: "https://www.amazon.co.jp/dp/B086WCHPK1?th=1",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "chọn loại a. Bath towel, set off 3, có nhiều màu: https://www.amazon.co.jp/dp/B086WCHPK1?th=1",
  },
  {
    id: "g120",
    name: "Giá đỡ điện thoại ANDERY",
    link: "https://www.amazon.co.jp/dp/B0DN1S1YLV/?th=1",
    jpy: "1899y",
    vnd: "450k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "chỉ nhận đơn màu đen đang sale: https://www.amazon.co.jp/dp/B0DN1S1YLV/?th=1",
  },
  {
    id: "g121",
    name: "Nước tẩy vết cháy khét Yuwa Tipo trên vỉ bếp, xoong, nồi, chảo, bếp gas, bếp từ,... 300ml",
    link: "",
    jpy: "",
    vnd: "140k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Có sẵn siêu thị",
  },
  {
    id: "g122",
    name: "Cọ tẩy rửa nhà bếp, đồ gia dụng 3M Scotch-Brite K-505J chống trầy xước 11 x 22 x 6.2 cm",
    link: "",
    jpy: "",
    vnd: "150k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "chính là cây cọ c QA dùng trong clip này nhé: https://www.facebook.com/share/r/1J1uex3ceC/\n\ncó sẵn siêu thị",
  },
  {
    id: "g123",
    name: "Set hộp inox Neoflam",
    link: "",
    jpy: "",
    vnd: "1050k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Có sẵn siêu thị",
  },
  {
    id: "g124",
    name: "Viên uống NMN Premium 22050 Levante 90 viên",
    link: "",
    jpy: "",
    vnd: "lưu đơn siêu thị bth",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Có sẵn siêu thị, khách hỏi thì báo sắp về hàng, giá 750k",
  },
  {
    id: "g125",
    name: "Hộp hấp trứng lò vi sóng Akebono",
    link: "https://www.amazon.co.jp/dp/B000HI9BAA",
    jpy: "",
    vnd: "3 quả giá 390k, 2 quả tính bth",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Loại 3 quả 1173y: \nhttps://www.amazon.co.jp/dp/B000HI9BAA\nLoại 2 quả đã hết sale: https://www.amazon.co.jp/dp/B000HIB9G4/?th=1",
  },
  {
    id: "g126",
    name: "Máy triệt lạnh ulike",
    link: "https://item.rakuten.co.jp/ulike-store/ulikeme/?variantId=UlikeMe",
    jpy: "Tính giá thì trừ 13121y theo coupon, còn 19680y đến hết 15/9",
    vnd: "Tính bình thường, theo giá 19680y đến hết 15/9",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g127",
    name: "Ngũ cốc 24 loại hạt",
    link: "https://item.rakuten.co.jp/buono-buono/10007800-2pc/",
    jpy: "1000y cho set 2 gói",
    vnd: "Nhiều mức giá — 250k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\n250k/1 gói 400g, 450k/2 gói (800g)\nLưu đơn chú ý ghi rõ là 1 gói hay set 2 gói để đội đặt hàng còn biết nhé",
  },
  {
    id: "g128",
    name: "Dụng cụ tẩy cặn canxi Gekiochi-kun đầu kim cương nhân tạo làm sạch gương, kính, gốm sứ chống trầy xước",
    link: "",
    jpy: "",
    vnd: "220k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "có sẵn siêu thị",
  },
  {
    id: "g129",
    name: "Kẹp khăn",
    link: "https://item.rakuten.co.jp/office999/torukp/?variantId=r-sku00000002",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "Nhiều mức giá — 140k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá Yên chi tiết:\n998y set 2 cái\n1398y set 3 cái\n1698y set 4 cái\n\nGiá gồm cân chi tiết:\nMua 1 cái giá 140k, mua từ 2 cái trở lên giá 110k một cái\nLưu đơn chú ý lưu rõ là mua lẻ 1 cái hay mua set mấy cái để đội đặt hàng còn biết mà đặt cho hợp lý nhé",
  },
  {
    id: "g130",
    name: "Dung dịch thông tắc đường ống 800gr Rocket",
    link: "",
    jpy: "",
    vnd: "64k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Có sẵn siêu thị",
  },
  {
    id: "g131",
    name: "Sữa cao",
    link: "",
    jpy: "",
    vnd: "Nhiều mức giá — 550k...",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Có sẵn siêu thị, lưu đơn siêu thị bth. \n\nThông tin tư vấn:\n- Tại sao pha Asumiru không tan mịn như sữa? Vì thực ra em này không phải sữa bột thông thường, mà là bột bổ sung dinh dưỡng với nhiều thành phần khác nhau. Em gọi “sữa Asumiru” cho quen miệng thôi 😅 nên khi pha thấy khác sữa bình thường cũng k vấn đề gì cả c nhé.\n- Đây là dòng xếp hàng đầu trong dòng bột dinh dưỡng của trẻ em Nhật trong nhiều năm, được đánh giá cao nhất tại Nhật ạ. Cung cấp cho trẻ các chất sau: ✔ L’arginin giúp bé tăng trưởng chiều cao và tăng sức đề kháng. ✔ MK7 từ món Natto của người Nhật giúp đưa canxi vào tận xương, tăng Collagen phát triển xương nhanh và dài... ✔ Vitamin D giúp canxi hấp thu vào cơ thể 1 cách tối đa 🍬 Nhóm Zinc - Arginine - Placenta bổ sung dưỡng chất tăng trưởng chiều cao, làm dài xương. 🦀 3 loại Canxi tăng mật độ xương, phát triển thể chất cứng cáp, vững vàng cho trẻ. 🐣 8 loại Vitamin, khoáng chất thiết yếu, DHA, EPA bổ sung năng lượng cho các hoạt động của bé.\n- Uống loại này rồi thì không cần thiết phải dùng thêm các loại tảo, canxi hay thực phẩm chức năng khác ạ, vì hàm lượng dinh dưỡng trong sản phẩm này rất cao, đã vượt trội hơn nhiều dòng sản phẩm khác.\n- Sản phẩm chứa các thành phần hoàn toàn tự nhiên, 4 thành phần quan trọng nhất gồm: hạt vừng, san hô, xương cá và tảo. trong đó Hạt vừng san hô và xương cá là nguồn canxi tự nhiên dễ hấp thụ nhất. Tảo xoắn dc coi là vua của các loại tpcn, đc Who khuyên dùng với hơn 50 loại chất tốt cho sk cung cấp vitamin, khoáng chất, và chất đạm, và đặc biệt là hiệu suất hấp thụ cao. Hoàn toàn không có chất bảo quản hay màu nhân tạo, k chất hóa học, đc kiểm soát chất lượng nghiêm ngặt an toàn cho sức khỏe của trẻ, không gây dậy thì sớm\n- Nên dùng trong bao lâu ? Dùng thường xuyên và kéo dài nhiều năm càng tốt. Khuyến cáo nên kiên trì 1 năm liên tục. Và như bên Nhật là kéo dài suốt nhiều năm, đặc biệt giai đoạn từ 4-15 tuổi là cực kì cần thiết.\n- Dùng bao lâu thì thấy hiệu quả: Dạ còn tùy vào thể chất và nguồn gen nên hiệu quả nhanh chậm trên tùy bé cũng sẽ khác nhau. Quan trọng nhất vẫn là bổ sung đều đặn trong suốt giai đoạn con phát triển, kết hợp ăn uống đủ chất, vận động nhiều và ngủ đủ. Kiên trì 1 thời gian mới thấy hiệu quả rõ rệt ạ.\n- Cách dùng: \n👉 3–10 tuổi: Asumiru thường – gói trắng 180g\n• 3–5 tuổi: khoảng 3g/ngày\n• 6–10 tuổi: khoảng 6g/ngày\n👉 10–18 tuổi: Super Asumiru – gói đỏ 330g - khoảng 11g/ngày\n- Dùng cho bé từ 3-4 tuổi trở lên, với các bé bị dị ứng hoặc bất dung nạp sữa thì nên hỏi thêm ý kiến bác sĩ trc khi dùng\n- Một gói dùng trong khoảng 30 ngày. - Vị cacao dễ uống bé nào cũng thích\n\nGiá gồm cân chi tiết:\nLưu đơn siêu thị bình thường. Báo giá dùng nguyên văn câu dưới đây cho c\n\nDạ em chào c ạ\n- Dòng sữa cao màu trắng cho bé từ 3-10t giá 550k gói 180g\n- Dòng sữa cao Super màu đỏ cho bé trên 10-18t giá 850k gói 330g\nĐây là dòng sản phẩm bột dinh dưỡng xếp hàng đầu cho trẻ em Nhật trong rất nhiều năm, được đánh giá cao nhất tại Nhật ạ. Hàm lượng dinh dưỡng cao, thành phần tự nhiên k chất bảo quản, k màu nhân tạo, k chất hóa học, k gây dậy thì sớm, đc kiểm soát chất lượng nghiêm ngặt an toàn cho sức khỏe của trẻ ạ. Một gói dùng đc khoảng 1 tháng c nhé",
  },
  {
    id: "g132",
    name: "Kẹo dẻo bổ sung omega 3 Fish OiL",
    link: "",
    jpy: "",
    vnd: "590k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Có sẵn siêu thị",
  },
  {
    id: "g133",
    name: "Cân tiểu ly DRETEC",
    link: "https://www.amazon.co.jp/dp/B0CNBQB6P1?th=1",
    jpy: "1552y",
    vnd: "390k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g134",
    name: "Máy hút bụi Dyson V10 Fluffy",
    link: "https://item.rakuten.co.jp/dyson/593813-01/",
    jpy: "",
    vnd: "Tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g135",
    name: "Kao Toilet Magiclean khử mùi hôi, làm sạch cặn bẩn trong lòng bồn cầu",
    link: "",
    jpy: "",
    vnd: "195k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Sắp về sẵn, hẹn khách 1 tuần sau có hàng nhé. Ôm từ ngày 8/9, khoảng 1 tuần sau từ ngày này thì check thử trên file Giá sản phẩm bên siêu thị xem có sẵn chưa",
  },
  {
    id: "g136",
    name: "Vịt tách lòng đỏ trứng",
    link: "https://www.amazon.co.jp/dp/B0856QQB6M/",
    jpy: "",
    vnd: "900y trở xuống đều tính giá 250k gồm cân được nhé",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g137",
    name: "Bình ủ trà cà phê cold brew Hario 650ml",
    link: "https://www.amazon.co.jp/dp/B0859JZPHW?th=1",
    jpy: "",
    vnd: "Nhận cả loại đen và trắng, từ 1764y trở xuống đều tính 450k gồm cân",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g138",
    name: "Lọc nước tại vòi Cleansui MD101-NC",
    link: "https://www.amazon.co.jp/dp/B003AZZS3Q/?th=1",
    jpy: "",
    vnd: "Nhiều mức giá — 990k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "-Lọc nước CLEANSUI MD101: https://www.amazon.co.jp/dp/B003AZZS3Q/?th=1 \n\n- Khách muốn mua thêm lõi lọc nước thay thế CLEANSUI MDC01 thì mua tại link này, ở link này có loại 1 cái, set 2 cái hoặc set 3 cái: https://www.amazon.co.jp/dp/B010AL4PBS?th=1\n\nGiá gồm cân chi tiết:\n- Máy lọc đang có giá 3975y thì tính 990k gồm cân (mua cái này thì đã có sẵn 1 thân máy kèm 1 lõi lọc r nhé)\n- Set 3 lõi lọc thay thế giá 6980y thì tính 1600k gồm cân\n- Set 2 lõi lọc thay thế giá 6980y thì tính 1375k gồm cân\n- Lõi lọc thay thế lẻ 1 cái 3636y tính 795k gồm cân",
  },
  {
    id: "g139",
    name: "Hộp đựng thuốc chia ngăn Shimoyama",
    link: "https://item.rakuten.co.jp/ignis/2202sd358/",
    jpy: "Giá 1980y code 20% áp dụng tới hết 14/9",
    vnd: "450k gồm cân, áp dụng tới hết 14/9",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g140",
    name: "Nắp đậy silicon ToYo Case",
    link: "https://www.amazon.co.jp/dp/B0CWGC9J3M/?th=1",
    jpy: "",
    vnd: "Nhiều mức giá — 280k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\nMàu cam - 15cm - 980y -> 280k gồm cân\nMàu hồng - 20cm - 1078y -> 340k gồm cân",
  },
  {
    id: "g141",
    name: "Giấy lau mặt Nanoni 80 tờ",
    link: "",
    jpy: "",
    vnd: "140k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "sẵn siêu thị, sắp về",
  },
  {
    id: "g142",
    name: "Bàn ủi hơi nước cầm tay EUE",
    link: "https://www.amazon.co.jp/dp/B0BVYM7YNG/?th=1",
    jpy: "",
    vnd: "nhận đơn cả màu xám và màu trắng, cứ giá 3179y trở xuống thì tính 960k gồm cân",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g143",
    name: "Tương miso 𝐌𝐚𝐫𝐮𝐤𝐨𝐦𝐞",
    link: "https://www.amazon.co.jp/dp/B002PH3TZE/?th=1",
    jpy: "496y",
    vnd: "280k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g144",
    name: "Rong biển đậu hũ khô Shinshu",
    link: "https://item.rakuten.co.jp/shikisaido/4945959501276/",
    jpy: "540y",
    vnd: "190k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g145",
    name: "Xịt chống muỗi Fumakilla Angel's Skin Vape Premium Mist 200ml, cho bé từ 0 tháng tuổi",
    link: "https://item.rakuten.co.jp/sundrug/4902424440621/",
    jpy: "746y",
    vnd: "230k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g146",
    name: "Dầu nhuyễn thể Omega 3 KORI Nhật Bản - hộp 152 viên",
    link: "",
    jpy: "",
    vnd: "580k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "sẵn siêu thị, sắp về",
  },
  {
    id: "g147",
    name: "Tuýp kem bôi đa năng Oronine H Ointment 50g (muỗi, côn trùng,...)",
    link: "",
    jpy: "",
    vnd: "160k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "sẵn siêu thị, sắp về",
  },
  {
    id: "g148",
    name: "Set kem đánh răng Lion ex 5 hộp",
    link: "",
    jpy: "",
    vnd: "360k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "sẵn siêu thị, sắp về",
  },
  {
    id: "g149",
    name: "Đũa sợi thủy tinh Asahi Koyo",
    link: "",
    jpy: "",
    vnd: "Nhiều mức giá — 150k...",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "sẵn siêu thị, sắp về\n\nGiá gồm cân chi tiết:\nset 5 đôi: 150k\nset 10 đôi: 280k",
  },
  {
    id: "g94",
    name: "Bình rót kiêm xịt dầu Takagi 450ml",
    link: "https://www.amazon.co.jp/dp/B0GSD7VW1Y",
    jpy: "698y",
    vnd: "290k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g95",
    name: "Thùng ủ muối dưa LOCK & LOCK",
    link: "https://www.amazon.co.jp/dp/B07W4G5JLW?th=1",
    jpy: "",
    vnd: "tính bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Thùng 2.6l màu đỏ: https://www.amazon.co.jp/dp/B07W4G5JLW?th=1\n\nThùng 6l màu xanh: https://www.amazon.co.jp/dp/B07W4GJDNM?th=1",
  },
  {
    id: "g96",
    name: "Kéo nhà bếp Kaneka Tools 084041 Tsubame Sanjo",
    link: "https://www.amazon.co.jp/dp/B001TUTI94?th=1",
    jpy: "2483y",
    vnd: "590k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Chỉ nhận phân loại Removable: https://www.amazon.co.jp/dp/B001TUTI94?th=1",
  },
  {
    id: "g97",
    name: "Bộ 4 giá đỡ điều khiển từ xa XYOFUN",
    link: "https://www.amazon.co.jp/dp/B0DCNHB5FT?th=1",
    jpy: "750y",
    vnd: "200k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Có 4 lựa chọn mix màu, nhớ hỏi khách chọn mix màu hay bộ 4c trắng, hay bộ 4c đen để còn lưu đơn nhé: https://www.amazon.co.jp/dp/B0DCNHB5FT?th=1",
  },
  {
    id: "g98",
    name: "Bình lọc dầu Wahei Freiz ER-7574 1.3l",
    link: "https://www.amazon.co.jp/dp/B014SV17C6/?th=1",
    jpy: "1225y",
    vnd: "380k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g99",
    name: "Máy hàn miệng túi mini",
    link: "https://www.amazon.co.jp/dp/B0HB6GKTRL/?th=1",
    jpy: "1999y",
    vnd: "Nhiều mức giá — 460k...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\n(có 2 màu gạch đỏ trong ảnh là k có hàng đâu, còn lại thì hỏi xem khách chọn màu nào hãy lưu đơn nhé)\n460k",
  },
  {
    id: "g100",
    name: "Kao Magiclean-xịt phân hủy dầu mỡ bếp, vỉ nướng, chảo",
    link: "https://www.amazon.co.jp/dp/B000TGMG3Y?th=1",
    jpy: "495y",
    vnd: "250k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g101",
    name: "Cây cọ khe rãnh Azuma",
    link: "https://www.amazon.co.jp/dp/B0BJCJGWPK/?th=1",
    jpy: "Màu trắng xám đều được: 692y",
    vnd: "190k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g102",
    name: "Cây lau đa năng Azuma",
    link: "https://www.amazon.co.jp/dp/B0BJCJTS35/?th=1",
    jpy: "Nhiều mức giá (xem ghi chú)",
    vnd: "460k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá Yên chi tiết:\nPhân loại \nRegular-main unit: 1832y",
  },
  {
    id: "g103",
    name: "Bàn chải cọ sàn + 2 miếng cọ thay thế Azuma",
    link: "https://www.amazon.co.jp/dp/B0F654B7SJ?th=1",
    jpy: "Phân loại Main unit + 2 spares: 1513y",
    vnd: "380k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g104",
    name: "Miếng mút xốp + hít nam châm Azuma",
    link: "https://www.amazon.co.jp/dp/B0BLXQVMZY/?th=1",
    jpy: "Phân loại  Regular-Sponge + Magnetic Hook: 589y",
    vnd: "150k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g105",
    name: "Rổ vo gạo thông minh CÓME COLLE của Akenobo",
    link: "https://item.rakuten.co.jp/chubo-kitchen/054146002/",
    jpy: "1155y",
    vnd: "310k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g106",
    name: "Bộ dụng cụ làm sữa chua hy lạp nhanh Akebi Sangyo",
    link: "https://www.amazon.co.jp/dp/B08KGT8K4L?th=1",
    jpy: "1815y",
    vnd: "490k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g107",
    name: "Nồi áp suất Pearl Metal",
    link: "https://www.amazon.co.jp/dp/B000BY8KH0/?th=1",
    jpy: "",
    vnd: "Xem ghi chú giá",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Giá gồm cân chi tiết:\nhỏi xem khách chọn dung tích bao nhiêu lít rồi cứ tính bình thường nhé",
  },
  {
    id: "g108",
    name: "Miếng dán khử mùi thùng rác",
    link: "https://item.rakuten.co.jp/sundrug/4901070120222/",
    jpy: "228y",
    vnd: "90k set 2 cái",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g109",
    name: "Son gió Shiseido",
    link: "https://www.amazon.co.jp/dp/B00I0O2PSI/?th=1",
    jpy: "771",
    vnd: "195k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },

];
