// lib/giadungSeed.js
// Danh sách sản phẩm "Gia dụng + Thực phẩm chức năng" được tự động điền từ
// file Google Sheet "BẢNG GIÁ GỒM CÂN" (sheet "GIA DỤNG, THỰC PHẨM CHỨC NĂNG")
// do chủ shop cung cấp. Dùng làm dữ liệu khởi tạo (seed) một lần khi tab này
// còn trống — sau khi người dùng tự thêm/sửa/xoá sản phẩm, danh sách thật sẽ
// được lưu và seed này không còn tác dụng nữa.
export const SEED_GIADUNG = [
  {
    id: "g01",
    name: "Viên uống bổ sung Magie Health+ (60 viên nén, dùng 30 ngày)",
    link: "",
    jpy: "",
    vnd: "Theo giá sẵn",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Hàng bán sẵn, xem giá sẵn hiện có.",
  },
  {
    id: "g02",
    name: "Lọ chống mọt gạo",
    link: "https://www.amazon.co.jp/dp/B002ROPIFE/?th=1",
    jpy: "",
    vnd: "150k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "cQA nhập về bán sẵn rồi nên lưu đơn thì lưu sẵn siêu thị nhé, giá 150k.\nBài đăng: https://www.facebook.com/reel/1891080824897410",
  },
  {
    id: "g03",
    name: "Giá phơi bát đĩa gấp gọn Pearl Metal HB-6355 Kitchen Mate",
    link: "https://www.amazon.co.jp/dp/B09TSDXK4T",
    jpy: "885y",
    vnd: "390k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/1HURtWU6Gu/",
  },
  {
    id: "g04",
    name: "Lọ xay muối tiêu Asvel",
    link: "https://www.amazon.co.jp/dp/B003NUSDDK/",
    jpy: "825y",
    vnd: "260k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://web.facebook.com/share/r/1H9zamHFJQ/",
  },
  {
    id: "g05",
    name: "Chảo gang TETSUNAGI (vuông & tròn, nhiều kích thước)",
    link: "https://www.amazon.co.jp/dp/B0H2TYLN7J?th=1",
    jpy: "",
    vnd: "Không tính giá gồm cân, báo giá +KG bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Nhận order cả loại vuông và tròn với nhiều kích thước.\nBài đăng: https://web.facebook.com/share/p/1BRvBA7jd8/",
  },
  {
    id: "g06",
    name: "Bình đựng đá Atlas AWJB-A3900",
    link: "https://www.amazon.co.jp/dp/B0G293Z4Q3?th=1",
    jpy: "",
    vnd: "Không tính giá gồm cân, báo giá +KG bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Nhận order cả loại 2.3l và 3.9l với 2 màu khác nhau.\nBài đăng: https://web.facebook.com/share/p/1Bc8gSS2Jw/",
  },
  {
    id: "g07",
    name: "Máy hút bụi cầm tay mini Svoko",
    link: "https://www.amazon.co.jp/dp/B0DC6FB2C5?th=1",
    jpy: "2999y",
    vnd: "795k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/r/18nNpNhxrn/",
  },
  {
    id: "g08",
    name: "Quạt tuần hoàn Amazon",
    link: "https://www.amazon.co.jp/dp/B0C9ZT34H3",
    jpy: "6482y",
    vnd: "1790k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/1HGT3AmUmF/",
  },
  {
    id: "g09",
    name: "Vòi sen Refa",
    link: "https://www.amazon.co.jp/dp/B0G23VZNCX",
    jpy: "Màu trắng + màu bạc giá 35.000y, các màu còn lại giá 38.000y",
    vnd: "Màu trắng và bạc 6990k, còn lại 7590k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/r/1BYc7FbQVG/",
  },
  {
    id: "g10",
    name: "Cây lau nhà tắm LEC S-824 Gekochi-kun",
    link: "https://www.amazon.co.jp/-/en/dp/B01KUSQ50A?th=1",
    jpy: "",
    vnd: "Có loại cán ngắn và cán dài, có cả lựa chọn set 2 cái, mỗi loại 1 giá — không tính giá gồm cân, báo +KG như bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/1DTgVg7qUw/",
  },
  {
    id: "g11",
    name: "Nồi chiên điện Zojirushi",
    link: "https://www.amazon.co.jp/-/en/dp/B001RO4H7U",
    jpy: "",
    vnd: "Không tính giá gồm cân, báo giá +KG bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/18spDPwuBL/",
  },
  {
    id: "g12",
    name: "Máy sấy Komidy",
    link: "https://www.amazon.co.jp/Komidy/dp/B0GXFM564B?th=1",
    jpy: "",
    vnd: "Không tính giá gồm cân, báo giá +KG bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g13",
    name: "Khăn tắm sợi gai",
    link: "https://www.amazon.co.jp/dp/B003PBTWE6?th=1",
    jpy: "746y/cái",
    vnd: "190k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/reel/1008345242170469",
  },
  {
    id: "g14",
    name: "Máy làm đá bào",
    link: "https://www.amazon.co.jp/-/en/dp/B0BV1YRN8Y?th=1",
    jpy: "Loại màu be chạy bằng điện, loại màu xanh mint chạy bằng pin",
    vnd: "Tự tính giá trên web cộng cân nặng sản phẩm 1.2kg",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g15",
    name: "Lược gội đầu Mapepe",
    link: "https://www.amazon.co.jp/dp/B001H9NQ1I/?th=1",
    jpy: "638y",
    vnd: "250k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/r/1RMm7PN6XQ/",
  },
  {
    id: "g16",
    name: "Bộ dao kéo T-Fal tráng Titanium K13403",
    link: "https://www.amazon.co.jp/dp/B0GWKWBG16/?th=1",
    jpy: "4805y cả bộ 4 món",
    vnd: "980k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Có lựa chọn lẻ dao hoặc lẻ kéo.\nBài đăng: https://www.facebook.com/share/p/18mjP9oeJk/",
  },
  {
    id: "g17",
    name: "Bàn chải điện Baometi (kèm 8 đầu bàn chải thay thế)",
    link: "https://www.amazon.co.jp/dp/B0GX1K9T3N/?th=1",
    jpy: "Nhận gom 2 màu onyx và vanilla, giá 2980y và 2979y",
    vnd: "695k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/14q3idnkGHy/",
  },
  {
    id: "g18",
    name: "Bình nước Asvel 2L",
    link: "https://www.amazon.co.jp/-/en/dp/B0CZSPP7R3?th=1",
    jpy: "1192y/bình, 2384y/set 2 bình",
    vnd: "425k/bình, set 2 bình 795k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/1BQWb5Aqqh/",
  },
  {
    id: "g19",
    name: "Nồi chiên không dầu Wallfire",
    link: "https://www.amazon.co.jp/dp/B092ZS3LLB/",
    jpy: "",
    vnd: "Không tính giá gồm cân, báo giá +KG bình thường",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/173RhG7EWS/",
  },
  {
    id: "g20",
    name: "Hạt Chia",
    link: "",
    jpy: "",
    vnd: "Khách hỏi thì báo giá 350k/túi 300g",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Hàng có sẵn.\nBài đăng: https://www.facebook.com/share/r/1cvbdkRqy8/",
  },
  {
    id: "g21",
    name: "Sạc dự phòng 50.000mAh",
    link: "https://www.amazon.co.jp/dp/B0GSZ3D29K?th=1",
    jpy: "2849y",
    vnd: "690k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/1BUfSChD1o/",
  },
  {
    id: "g22",
    name: "Bình trà lõi lọc Asvel",
    link: "https://www.amazon.co.jp/dp/B085TTNXLD/?th=1",
    jpy: "999y",
    vnd: "290k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g23",
    name: "Máy xay cà phê điện BESROY",
    link: "https://www.amazon.co.jp/dp/B0B6RCRH22/?th=1",
    jpy: "2980y",
    vnd: "690k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/p/19DyxiuFA9/",
  },
  {
    id: "g24",
    name: "Set gội xả Bioliss",
    link: "https://item.rakuten.co.jp/rakuten24/4971710642414/",
    jpy: "1090y",
    vnd: "440k/cặp gội xả",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Màu vàng cho đầu nhiều dầu, màu cam cho tóc khô xơ hoặc dùng nhiều hóa chất.\nLink thay thế (Amazon): https://www.amazon.co.jp/dp/B0GTSSWWJD/\nBài đăng: https://www.facebook.com/share/p/18Nt22R6it/",
  },
  {
    id: "g25",
    name: "Tinh dầu thơm phòng cắm que Sawaday",
    link: "https://www.amazon.co.jp/dp/B0BYRRVN55/",
    jpy: "Màu vàng và xanh 496y, màu đen 1848y",
    vnd: "Màu vàng và màu xanh 190k, màu đen 220k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Màu vàng: https://www.amazon.co.jp/dp/B0BYRRVN55/\nMàu xanh: https://www.amazon.co.jp/dp/B0DGKPX854/\nMàu đen: https://www.amazon.co.jp/dp/B017I9P4I8/",
  },
  {
    id: "g26",
    name: "Chảo siêu nhẹ KAI",
    link: "https://www.amazon.co.jp/-/dp/B002GGRDSI/",
    jpy: "",
    vnd: "Dựa theo cân nặng sản phẩm từng size để tự tính giá gồm cân, tính chênh thêm khoảng 2 lạng so với cân nặng sản phẩm ghi trên web",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Chọn phân loại Frying Pan Induction Compatible, mỗi size 1 giá — chú ý hỏi khách chọn size nào thì báo giá size đó.\nBài đăng: https://www.facebook.com/share/p/1cMsa79JaK/",
  },
  {
    id: "g27",
    name: "Máy sấy chăn ga gối đệm chống mạt bụi Sintu",
    link: "https://www.amazon.co.jp/dp/B0GF86JSRR/",
    jpy: "5776y",
    vnd: "1395k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g28",
    name: "Máy xay Panasonic",
    link: "https://www.amazon.co.jp/dp/B09W5FZ8W3?th=1",
    jpy: "Chỉ nhận phân loại Entry: 8003y",
    vnd: "1890k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Bài đăng: https://www.facebook.com/share/r/18pW8PXJ7u/",
  },
  {
    id: "g29",
    name: "Nạo rau củ đa năng Shimomura Kihan 4 in 1",
    link: "https://www.amazon.co.jp/dp/B0793NSD3M?th=1",
    jpy: "1041y",
    vnd: "360k/1 set",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Màu trắng.",
  },
  {
    id: "g30",
    name: "Xịt tẩy nhà bếp KAO",
    link: "",
    jpy: "",
    vnd: "240k",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Tẩy bình giữ nhiệt, thớt,... Có sẵn siêu thị. C QA đăng trên tiktok của c QA.",
  },
  {
    id: "g31",
    name: "Táo đỏ",
    link: "https://www.amazon.co.jp/gp/aw/d/B0CZTFZHHK/?th=1",
    jpy: "1480y",
    vnd: "350k/1 gói 268g",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g32",
    name: "Kỷ tử",
    link: "https://www.amazon.co.jp/dp/B0D1RDRGNR/?th=1",
    jpy: "",
    vnd: "Gói 168g: sale còn 980y thì tính 290k gồm cân, không sale mà 1180y thì tính 335k gồm cân. Gói 328g: sale còn 1750y thì tính 480k gồm cân, không sale mà 1980y...",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Link gói 328g: https://www.amazon.co.jp/dp/B0D1RH31WP/?th=1",
  },
  {
    id: "g33",
    name: "Bột protein 1kg",
    link: "https://www.amazon.co.jp/dp/B01FRPR17W?th=1",
    jpy: "4360y",
    vnd: "1050k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g34",
    name: "Bột yến mạch OatMeal 1kg",
    link: "https://www.amazon.co.jp/dp/B0B46BHLY2/?th=1",
    jpy: "955y",
    vnd: "390k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g35",
    name: "7 loại hạt mix 350g",
    link: "https://www.amazon.co.jp/dp/B07XLX7LXJ/?th=1",
    jpy: "1000y",
    vnd: "330k",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "",
  },
  {
    id: "g36",
    name: "Các loại hạt nấu cùng cơm",
    link: "https://item.rakuten.co.jp/buono-buono/10007800-2pc/",
    jpy: "1000y",
    vnd: "250k/1 gói 400gr, 450k/2 gói tổng 800gr",
    orderType: "order",
    image: "",
    favorite: false,
    productNote: "Link trên là gói 2 túi tổng 800g. Link gói lẻ 400g thì phải hỏi lại đã.",
  },
  {
    id: "g37",
    name: "Thớt kháng khuẩn",
    link: "",
    jpy: "1280y",
    vnd: "450k (áp dụng cho giá yên 1280y)",
    orderType: "ready",
    image: "",
    favorite: false,
    productNote: "Hiện đã có sẵn siêu thị. Hàng siêu thị hết thì hỏi xem có về nữa không, chỉ khi nào không về thêm hàng siêu thị nữa thì mới nhận order theo giá trên.",
  },
];
